### ISSUE TITLE
ctypes.cdll error

### ISSUE THREAD

**Issue by gvossos** [MusicLang/musiclang_predict#25]
Hi, I'm unable to run sample scripts on Windows 11 using Python 3.11.8.

Python throws --> ctypes.CDLL(lib_path) error, 
--> musiclang\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode), 
--> FileNotFoundError: Could not find module '....\musiclang\Lib\site-packages\musiclang_predict\c\run.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Any suggestions?

**Comment by GamingDaveUk** [comment]
Same issue.
windows 11.
git cloned the repo
cd'd into it
created a virtual environment: python -m venv venv
activated the environment: venv\Scripts\activate
created a test.py with the github basic script contents word for word.
ran it and after it downloaded the model etc I got:
```
(venv) D:\AI\musiclang_predict>python test.py
Traceback (most recent call last):
  File "D:\AI\musiclang_predict\test.py", line 9, in <module>
    score = ml.predict(
  File "D:\AI\musiclang_predict\musiclang_predict\predict.py", line 68, in predict
    generated_text = run_transformer_model(
  File "D:\AI\musiclang_predict\musiclang_predict\chelpers.py", line 19, in run_transformer_model
    lib = load_library()
  File "D:\AI\musiclang_predict\musiclang_predict\chelpers.py", line 12, in load_library
    return ctypes.CDLL(lib_path)
  File "C:\Program Files\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\AI\musiclang_predict\musiclang_predict\c\run.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

I noticed in the readme it says to pip install it rather than clone it. so i tried that with a freshfolder, fresh virtual environment and got the following error:

```
 Running setup.py install for musiclang-predict ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mrgre\\AppData\\Local\\Temp\\pip-install-wm0d7_rn\\musiclang-predict_24899c5f909b4853b8c3943ef01a8f26\\setup.py'"'"'; __file__='"'"'C:\\Users\\mrgre\\AppData\\Local\\Temp\\pip-install-wm0d7_rn\\musiclang-predict_24899c5f909b4853b8c3943ef01a8f26\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mrgre\AppData\Local\Temp\pip-record-1b8gsgpe\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\mrgre\AppData\Roaming\Python\Python310\Include\musiclang-predict'
         cwd: C:\Users\mrgre\AppData\Local\Temp\pip-install-wm0d7_rn\musiclang-predict_24899c5f909b4853b8c3943ef01a8f26\
    Complete output (5 lines):
    running install
    running build
    running build_py
    error: [WinError 2] The system cannot find the file specified
    is called install
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mrgre\\AppData\\Local\\Temp\\pip-install-wm0d7_rn\\musiclang-predict_24899c5f909b4853b8c3943ef01a8f26\\setup.py'"'"'; __file__='"'"'C:\\Users\\mrgre\\AppData\\Local\\Temp\\pip-install-wm0d7_rn\\musiclang-predict_24899c5f909b4853b8c3943ef01a8f26\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mrgre\AppData\Local\Temp\pip-record-1b8gsgpe\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\mrgre\AppData\Roaming\Python\Python310\Include\musiclang-predict' Check the logs for full command output.
```

Side note: when going to get the error code again to share here, I forgot to activate my virtual environment.... that may end up being a costly mistake... time will tell but it does show its not the virtual environment effecting it.

**Comment by floriangardin** [comment]
I don't currently own a windows laptop so it's hard for me to debug that.
I don't know if the setup is failing for everyone on this os. If someone managed to get it to work on windows it would be great to let me know. Otherwise I am adding a disclaimer section on the readme.

If you clone it instead of pip install : you need to build the C dependencies (used for faster inference) yourself.
You need a C compiler, and there is a makefile in `musiclang_predict/c ` directory, it will build the lib. You can check the setup.py to see what is happening during the setup. 

I will work for a more robust setup, but if someone want to give a hand, it would be wonderful !

**Comment by gvossos** [comment]
Thanks for the note Florian.  Yes - hoping someone can help out.  For reference, I went down the pip install route.

**Comment by Akonyl** [comment]
Hi, decided to check this out and I believe I'm getting the same error while pip installing on w10 (if this project's still active).

```
  Building wheel for musiclang-predict (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      error: [WinError 2] The system cannot find the file specified
      is called install
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for musiclang-predict
  Running setup.py clean for musiclang-predict
Failed to build musiclang-predict
ERROR: Failed to build installable wheels for some pyproject.toml based projects (musiclang-predict)
```

Verbose:

```
Created temporary directory: C:\Users\MYUSER\AppData\Local\Temp\pip-unpack-_tfnw2xe
Building wheels for collected packages: musiclang-predict
  Created temporary directory: C:\Users\MYUSER\AppData\Local\Temp\pip-wheel-uqovu7za
  DEPRECATION: Building 'musiclang-predict' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'musiclang-predict'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for musiclang-predict (setup.py) ...   Destination directory: C:\Users\MYUSER\AppData\Local\Temp\pip-wheel-uqovu7za
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  error: [WinError 2] The system cannot find the file specified
  is called install
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\MYUSER\AppData\Local\Programs\Python\Python310\python.exe' -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize, traceback

  try:
      import setuptools
  except ImportError:
      print(
          "ERROR: Can not execute `setup.py` since setuptools failed to import in "
          "the build environment with exception:",
          file=sys.stderr,
      )
      traceback.print_exc()
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\MYUSER\\AppData\\Local\\Temp\\pip-install-53but3bu\\musiclang-predict_1a0652a0c97d40299aad9a108a540c9a\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d 'C:\Users\MYUSER\AppData\Local\Temp\pip-wheel-uqovu7za'
  cwd: C:\Users\MYUSER\AppData\Local\Temp\pip-install-53but3bu\musiclang-predict_1a0652a0c97d40299aad9a108a540c9a\\
error
  ERROR: Failed building wheel for musiclang-predict
  Running setup.py clean for musiclang-predict
  Running command python setup.py clean
  running clean
  'build\lib' does not exist -- can't clean it
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.10' does not exist -- can't clean it
Failed to build musiclang-predict
Remote version of pip: 25.1.1
Local version of pip:  25.1.1
Was pip installed by pip? True
ERROR: Failed to build installable wheels for some pyproject.toml based projects (musiclang-predict)
Exception information:
Traceback (most recent call last):
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 68, in wrapper
    return func(self, options, args)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 436, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Failed to build installable wheels for some pyproject.toml based projects (musiclang-predict)
Removed build tracker: 'C:\\Users\\MYUSER\\AppData\\Local\\Temp\\pip-build-tracker-453y4fx0'
```
